### ISSUE TITLE
API comments

### ISSUE THREAD

**Issue by ruyadorno** [rafaelrinaldi/transitionable-routes#1]
Just saw your tweet and decided to check out the project 😊 

Can't help but feel that _maybe_ having the entire API as a HOC that just sets `transition` as a prop - I know it may sound too much as functional stateless hype but I really dig that style these days for its flexibility.

It would make for simpler basic usage scenarios, e.g.:

```js
import { transitionableComponent } from 'transitionable-routes';

const About = props => <h1 style={{
  opacity: props.transition === 'enter' ? 1 : 0,
  transition: 'opacity 0.5s ease-out'
}}>About</h1>;

export default transitionableComponent(About);
```

Callbacks could possibly be defined within the HOC declaration too (redux style, easier to integrate with actions, etc).

```js
import { transitionableComponent } from 'transitionable-routes';

const willLeave = done => setTimeout(done, 1000))

const Contact = props => <h1 style={{
  transform: `translateY(${props.transition === 'enter' ? 0 : '20px'})`,
  opacity: transition === 'enter' ? 1 : 0,
  transition: 'all 1s ease-out'
}}>Contact</h1>;

export default transitionableComponent(Contact, { willLeave });
```

Anyways, just a quick 2 cents, sorry for the interruption 😊 just had some random thoughts and I thought it'd be nice to share (I know how lonely publishing open source stuff can be). Hope you can make something nice out of it! All the best 🎉

**Comment by rafaelrinaldi** [comment]
Hey Ruy thank you for the feedback. I do understand that this could be more Redux-style as you said. However I think it would be nothing less than sugar since the tricky part is not how to pass callbacks down to the component but rather how to communicate back and forth between the component and the switcher and how to sync things. This is where event emitters made sense to me.

With that being said I wouldn’t be opposed to have something like you’re suggesting, very similar to what React Router does by exposing things like `Router` along with `withRouter()` and friends.

Did I get your proposal right? Does my comment make sense?

Also feel free to send a PR.

**Comment by ruyadorno** [comment]
makes completely sense, worry not - it was just a brief after-lunch exercise thought, don't take it too seriously!
